export const id = require('./split/id.js')
export const getByClass = require('./split/getByClass.js')
export const ready = require('./split/ready.js')
export const trim = require('./split/trim.js')
export const addClass = require('./split/addClass.js')
export const removeClass = require('./split/removeClass.js')
export const hasClass = require('./split/hasClass.js')
export const getType = require('./split/getType.js')
export const each = require('./split/each.js')
export const toggleClass = require('./split/toggleClass.js')
export const getStyle = require('./split/getStyle.js')
export const onlyOneAddClass = require('./split/onlyOneAddClass.js')
export const isIe = require('./split/isIe.js')
export const prevent = require('./split/prevent.js')
export const mouseWheel = require('./split/mouseWheel.js')
export const backTop = require('./split/backTop.js')
export const vol_css = require('./split/vol_css.js')
export const apd_css = require('./split/apd_css.js')
export const getRandom = require('./split/getRandom.js')
export const convertTime = require('./split/convertTime.js')
export const getNowTime = require('./split/getNowTime.js')
export const getNearTime = require('./split/getNearTime.js')
export const getScrollPosition = require('./split/getScrollPosition.js')
export const removeElement = require('./split/removeElement.js')
export const addScript = require('./split/addScript.js')
export const loadStyle = require('./split/loadStyle.js')
export const getRelativePos = require('./split/getRelativePos.js')
export const getImgSize = require('./split/getImgSize.js')
export const getWindowSize = require('./split/getWindowSize.js')
export const setCookie = require('./split/setCookie.js')
export const getCookie = require('./split/getCookie.js')
export const removeCookie = require('./split/removeCookie.js')
export const isInVisibleArea = require('./split/isInVisibleArea.js')
export const getAroundIndex = require('./split/getAroundIndex.js')
export const blendJson = require('./split/blendJson.js')
export const numThousandth = require('./split/numThousandth.js')
export const getJsPath = require('./split/getJsPath.js')
export const blendArr = require('./split/blendArr.js') // 合并数组
export const unique = require('./split/unique.js')
export const isEmptyData = require('./split/isEmptyData.js')
export const getRandomColor = require('./split/getRandomColor.js')
export const throttle = require('./split/throttle.js') // 节流函数
export const getEventTarget = require('./split/getEventTarget.js') //获取发生事件的对象
export const clone = require('./split/clone.js')//克隆
export const reduce = require('./split/reduce.js')
export const fillHtml = require('./split/fillHtml.js')
export const getFunName = require('./split/getFunName.js')//获取函数名
export const unbind = require('./split/unbind.js')
export const bind = require('./split/bind.js')
export const bindEasy = require('./split/bindEasy.js')
export const click = require('./split/click.js')
export const clickEasy = require('./split/clickEasy.js')
export const unclick = require('./split/unclick.js')
export const atBottomLoad = require('./split/atBottomLoad.js')
export const numZero = require('./split/numZero.js'); // 数字小于10，在前面加0
export const https = require('./split/https.js'); // url转https
export const split = require('./split/split.js'); // 
export const defaultType = require('./split/defaultType.js');
export const getQuery = require('./split/getQuery.js');
export const polling = require('./split/polling.js');
export const getFromArrByKey = require('./split/getFromArrByKey.js');
export const removeEmptyKey = require('./split/removeEmptyKey.js');
export const toNumber = require('./split/toNumber.js');
export const convertTimeStamp = require('./split/convertTimeStamp.js');
export const transTimeToRecent = require('./split/transTimeToRecent.js');
export const isPrice = require('./split/isPrice.js');
export const getMonthInfo = require('./split/getMonthInfo.js');
export const getUserFromIdCard = require('./split/getUserFromIdCard.js');
export const replaceCustom = require('./split/replaceCustom.js');
export const fuzzySearch = require('./split/fuzzySearch.js');
export const bus = require('./split/bus.js');
export const imgErr = require('./split/imgErr.js');
export const clear = require('./split/clear.js');
export const fixed = require('./split/fixed.js');
export const html = require('./split/html.js');
export const numLimit = require('./split/numLimit.js');
export const map = require('./split/map.js');
export const objectAssemble = require('./split/objectAssemble.js');
export const isPhone = isPhone('./split/isPhone.js');
// 不兼容的
export const done = require('./split/advance/done.js');
export const obtain = require('./split/advance/obtain.js');
export const sleep = require('./split/advance/sleep.js');

