var bestimeGroup = {
  _Array: require('./split/_Array.js'),
  _Boolean: require('./split/_Boolean'),
  _Function: require('./split/_Function'),
  _Number: require('./split/_Number'),
  _Object: require('./split/_Object'),
  _String: require('./split/_String'),
  addClass: require('./split/addClass'),
  average: require('./split/average'),
  barCode: require('./split/barCode'),
  bind: require('./split/bind'),
  clear: require('./split/clear'),
  clone: require('./split/clone'),
  convertTime: require('./split/convertTime'),
  createStyleElement: require('./split/createStyleElement'),
  createUUID: require('./split/createUUID'),
  defaultType: require('./split/defaultType'),
  drag: require('./split/drag'),
  each: require('./split/each'),
  fillHtml: require('./split/fillHtml'),
  fixed: require('./split/fixed'),
  getByClass: require('./split/getByClass'),
  getById: require('./split/getById'),
  getCookie: require('./split/getCookie'),
  getData: require('./split/getData'),
  getQuery: require('./split/getQuery'),
  getRandom: require('./split/getRandom'),
  getRelativePos: require('./split/getRelativePos'),
  getScrollPosition: require('./split/getScrollPosition'),
  getStyle: require('./split/getStyle'),
  getType: require('./split/getType.js'),
  getWindowSize: require('./split/getWindowSize'),
  hasClass: require('./split/hasClass'),
  isArray: require('./split/isArray'),
  isEmpty: require('./split/isEmpty'),
  isFunction: require('./split/isFunction'),
  isNumber: require('./split/isNumber'),
  isObject: require('./split/isObject'),
  isPhone: require('./split/isPhone'),
  isString: require('./split/isString'),
  loading: require('./split/loading'),
  loopFunc: require('./split/loopFunc'),
  numberMax: require('./split/numberMax'),
  numberMin: require('./split/numberMin'),
  onDomRoll: require('./split/onDomRoll'),
  Parabola: require('./split/Parabola'),
  prevent: require('./split/prevent'),
  removeClass: require('./split/removeClass'),
  removeCookie: require('./split/removeCookie'),
  removeElement: require('./split/removeElement'),
  setCookie: require('./split/setCookie'),
  split: require('./split/split'),
  trim: require('./split/trim'),
  unbind: require('./split/unbind'),
  unique: require('./split/unique')
};

module.exports = !function (name) {
  window[name] = window['ns'] = bestimeGroup;
} ('bestime');

