var bestimeGroup = {
  id                : require('./split/id.js'),
  getByClass        : require('./split/getByClass.js'),
  ready             : require('./split/ready.js'),
  trim              : require('./split/trim.js'),
  addClass          : require('./split/addClass.js'),
  removeClass       : require('./split/removeClass.js'),
  hasClass          : require('./split/hasClass.js'),
  getType           : require('./split/getType.js'),
  each              : require('./split/each.js'),
  toggleClass       : require('./split/toggleClass.js'),
  getStyle          : require('./split/getStyle.js'),
  onlyOneAddClass   : require('./split/onlyOneAddClass.js'),
  isIe              : require('./split/isIe.js'),
  prevent           : require('./split/prevent.js'),
  mouseWheel        : require('./split/mouseWheel.js'),
  backTop           : require('./split/backTop.js'),
  vol_css           : require('./split/vol_css.js'),
  apd_css           : require('./split/apd_css.js'),
  getRandom         : require('./split/getRandom.js'),
  convertTime       : require('./split/convertTime.js'),
  getNowTime        : require('./split/getNowTime.js'),
  getNearTime       : require('./split/getNearTime.js'),
  getScrollPosition : require('./split/getScrollPosition.js'),
  removeElement     : require('./split/removeElement.js'),
  addScript         : require('./split/addScript.js'),
  loadStyle         : require('./split/loadStyle.js'),
  getRelativePos    : require('./split/getRelativePos.js'),
  getImgSize        : require('./split/getImgSize.js'),
  getWindowSize     : require('./split/getWindowSize.js'),
  setCookie         : require('./split/setCookie.js'),
  getCookie         : require('./split/getCookie.js'),
  removeCookie      : require('./split/removeCookie.js'),
  isInVisibleArea   : require('./split/isInVisibleArea.js'),
  getAroundIndex    : require('./split/getAroundIndex.js'),
  blendJson         : require('./split/blendJson.js'),
  numThousandth     : require('./split/numThousandth.js'),
  getJsPath         : require('./split/getJsPath.js'),
  blendArr          : require('./split/blendArr.js'),
  unique            : require('./split/unique.js'),
  isEmptyData       : require('./split/isEmptyData.js'),
  getRandomColor    : require('./split/getRandomColor.js'),
  throttle          : require('./split/throttle.js'),
  getEventTarget    : require('./split/getEventTarget.js'),
  clone             : require('./split/clone.js'),
  reduce            : require('./split/reduce.js'),
  fillHtml          : require('./split/fillHtml.js'),
  getFunName        : require('./split/getFunName.js'),
  unbind            : require('./split/unbind.js'),
  bind              : require('./split/bind.js'),
  bindEasy          : require('./split/bindEasy.js'),
  click             : require('./split/click.js'),
  clickEasy         : require('./split/clickEasy.js'),
  unclick           : require('./split/unclick.js'),
  atBottomLoad      : require('./split/atBottomLoad.js'),
  numZero           : require('./split/numZero.js'),
  https             : require('./split/https.js'),
  split             : require('./split/split.js'),
  defaultType       : require('./split/defaultType.js'),
  polling           : require('./split/polling.js'),
  getQuery          : require('./split/getQuery.js'),
  getFromArrByKey   : require('./split/getFromArrByKey.js'),
  removeEmptyKey    : require('./split/removeEmptyKey.js'),
  toNumber          : require('./split/toNumber.js'),
  convertTimeStamp  : require('./split/convertTimeStamp.js'),
  transTimeToRecent : require('./split/transTimeToRecent.js'),// 少用，以后去掉
  isPrice           : require('./split/isPrice.js'),
  getMonthInfo      : require('./split/getMonthInfo.js'),
  replaceCustom     : require('./split/replaceCustom.js'),
  fuzzySearch       : require('./split/fuzzySearch.js'),
  bus               : require('./split/bus.js'),
  sleep             : require('./split/advance/sleep.js'),// 不兼容
  imgErr            : require('./split/imgErr.js'),
  clear             : require('./split/clear.js'),
  fixed             : require('./split/fixed.js'),
  html              : require('./split/html.js'),
  numLimit          : require('./split/numLimit.js'),
  objectAssemble    : require('./split/objectAssemble.js'),
  isPhone           : require('./split/isPhone.js'),
  loopFunc          : require('./split/loopFunc.js')
};

module.exports = !function (name) {
  window[name] = window['ns'] = bestimeGroup;
  ns.CSSAPDBOX = ns.apd_css();
	ns.CSSVOLBOX = ns.vol_css();
} ('bestime');

